// pertemuan-23-24-25-konsumsi-api-asinkron-jwt-spa/react/src/components/PageHeader.jsx
// Solusi Referensi - Pertemuan 17-18: Komponen presentational sederhana (hanya menerima props)

import { Link } from "react-router-dom";

function PageHeader({ judul }) {
  return (
    <header className="page-header">
      <h1>{judul}</h1>
      <nav>
        <Link to="/">Daftar Mahasiswa</Link>
        {" | "}
        <Link to="/tentang">Tentang</Link>
      </nav>
    </header>
  );
}

export default PageHeader;

// pertemuan-19-20-build-tools-cli-spa/angular/src/app/components/page-header/page-header.component.ts
// Solusi Referensi - Pertemuan 17-18: Komponen presentational sederhana (hanya menerima @Input)

import { Component, Input } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-page-header',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './page-header.component.html',
})
export class PageHeaderComponent {
  @Input() judul!: string;
}
