// pertemuan-17-18-arsitektur-komponen-spa/react/src/components/MahasiswaList.jsx
// Solusi Referensi - Pertemuan 17-18: Komponen induk, mengelola data & merender banyak MahasiswaCard

import MahasiswaCard from "./MahasiswaCard";

function MahasiswaList({ mahasiswa }) {
  if (mahasiswa.length === 0) {
    return <p className="empty">Tidak ada mahasiswa yang cocok.</p>;
  }

  return (
    <div className="mahasiswa-list">
      {mahasiswa.map((m) => (
        <MahasiswaCard key={m.id} nama={m.nama} nim={m.nim} />
      ))}
    </div>
  );
}

export default MahasiswaList;

// pertemuan-21-22-form-validasi-spa/angular/src/app/components/mahasiswa-list/mahasiswa-list.component.ts
// Solusi Referensi - Pertemuan 17-18: Komponen induk, merender banyak MahasiswaCard

import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Mahasiswa } from '../../mahasiswa.model';
import { MahasiswaCardComponent } from '../mahasiswa-card/mahasiswa-card.component';

@Component({
  selector: 'app-mahasiswa-list',
  standalone: true,
  imports: [CommonModule, MahasiswaCardComponent],
  templateUrl: './mahasiswa-list.component.html',
})
export class MahasiswaListComponent {
  @Input() mahasiswa: Mahasiswa[] = [];
}
